### ISSUE TITLE
Move documentation to main repo

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#144]
**Is your feature request related to a problem? Please describe.**
It's really hard to keep the documentation in sync with the version of our main repo.

**Describe the solution you'd like**
The docs should live in the `docs/` directory of our main repo. As part of that, our PR template needs to be adjusted. It currently asks you to point to a PR in the docs repository, which we don't need anymore

### ToDo
- [x] Move docs to main repo
- [x] Adjust PR template
- [x] Point GitBook to new location in main repo

**Additional context**
This issue has been discussed in the telegram group. Other projects (mainly rust) has documentation in the main repository, which is where this idea comes from.
