### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by pouya-eghbali** [clio-lang/clio#71]
Dependencies aren't handled correctly. No `package.json` is generated (See #69) and no dependencies are installed. Dependencies should be listed in the `package.json` and the compiler should do a `npm install` in `dest/` after generating this file.

### ToDo

- [x] Generate package.json when calling `clio build` 
- [x] Install required clio dependencies to `node_modules` of build dir
- [x] Install required npm dependencies to `node_modules` of build dir
- [x] Add node dependencies field to toml
- [x] Remove build directory from templates
