### ISSUE TITLE
Build command should consider clio.toml to decide where to put bundle

### ISSUE THREAD

**Issue by andreyluiz** [clio-lang/clio#87]
**Is your feature request related to a problem? Please describe.**
`clio build` is sending the compiled files to `.clio/target/node` by default. 

**Describe the solution you'd like**
Not considering the `--destination` parameter override, the output directory for the build command should be configured from `clio.toml`. An example toml config could look like this:

```toml
[build]
directory = "build"
target = "node"

[target.node]
directory = "src"
target = "node"

[target.browser]
directory = "src"
target = "browser"
```

**Describe alternatives you've considered**
We should create two fields on `clio.toml`:

- `target`: to give a hint to the compiler for what target is this build;
- `build`: as discussed on Telegram, to store in which directory to put the builds (default to `build`).

The resulting compiled JavaScript files should be placed in `${build}/${target}`.

**Additional context**
The build command should have a `--target` override to build a specific directory to a specific target. This way, the programmer can generate a project for browser target, but can compile a host for node target using this feature.

### ToDo

- [ ]  Add fields to `packageConfig`
- [ ] Update template repositories
- [ ] Let command line flag override toml

**Comment by garritfra** [comment]
Closed by #89
